### ISSUE TITLE
t-SNE widget in release does not work if installed as an add-on to Orange

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3-single-cell#323]
##### Single Cell version
0.9, installed through the add-on dialog

##### Orange version
3.18 dmg package

##### Actual behavior
t-SNE widget from singlecell shows "Error during optimization: __init__.py got an unexpected keyword argument 'n_iter_without_preprocess'. 

##### Steps to reproduce the behavior
Open 030-Scowcase-Clustering.ows

##### Additional info (worksheets, data, screenshots, ...)
That widget was moved to Orange afterwards, but it still in the current official version.

**Comment by lanzagar** [comment]
And on master there is a different problem - the tSNE widget has been removed from singlecell but the mentioned workflow still tries to use it.
-> The worflow should be updated to use Orange's tSNE, saved again, and a new version of the addon released
Maybe @mstrazar can help?

**Comment by markotoplak** [comment]
@lanzagar and @mstrazar, I think the old workflow should also work as is, because we can set "replaces" to widgets? Someone forgot to specify it in owtsne when it was moved to Orange.

**Comment by lanzagar** [comment]
I think "replaces" was not used intentionally in this case. As you noticed the two widgets are not exactly the same. I am not sure about the extent of changes from the top of my head, at least the backend tsne library was changed, I think some gui settings too, not sure about widget outputs.
This was not a widget move inside Orange (or even from Prototypes to core), so I don't think we need to add compatibility code for a new widget to support a prototype version that was used in another addon.
We should however fix and update single-cell to make sure everything is working with the newest Orange now, since we are coming close to the first official (1.0) release. We can worry about backwards compatibility from that point on :)

**Comment by BlazZupan** [comment]
Fixed, single-cell specific t-SNE widget removed, Orange's takes the role as the one and only one.
